### ISSUE TITLE
CDN In front of IMGiX

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/brunstadtv#326]
T31he current plan on IMGiX includes 500Gb of bandwidth, while our usage at the moment is significantly higher as shown below

![Untitled31](https://user-images.githubusercontent.com/88234679/235908522-8bd2b3d7-8693-48a6-be54-3302a23a4259.png)

We should put a Cloudfront distribution in front of it in order to cache the images and serve them via our “own” CDN.

**Comment by KillerX** [comment]
@fredrikved this needs to be changed on the backend only right, as the urls are generated there.

**Comment by fredrikved** [comment]
@KillerX Yes, just an environment variable

**Comment by fredrikved** [comment]
New domain deployed. Traffic to imgix should decrease.
