### ISSUE TITLE
Crowdin integration for localizing content

### ISSUE THREAD

**Issue by andreasgan** [bcc-code/brunstadtv#4]
# Description
We don't want to reinvent a translation system in the backend, so we want to integrate with crowdin.
The admin-interface should only operate on the primary language, which is currently Norwegian.

# High level flow
New content:
- An admin adds new episode
- An admin clicks "send to translation"
- Content appears in crowdin (crowdin notifies translators automatically via email)

Updates:
- An admin edits an existing episode
  - Optional checkbox to bypass translation (for minor changes).
- Content reappears in crowdin

On finished translations:
- Synced and available immediately if possible

# Technical details
Translation tables are all the tables ending with _t

# Extra notes
- If you use webhooks, maybe receive it with a function and push to [pub/sub](https://cloud.google.com/pubsub/docs/overview) to make sure we dont lose any.
- This should be a generic standalone service which we can copy-paste when integrating with other systems.
- It should run on google cloud run.
- Whatever we make should be compatible with enabling [in-context localization](https://support.crowdin.com/in-context-localization/#integration)
- The "files" in crowdin should probably be HTML files with styles for title, description, etc.

**Comment by andreasgan** [comment]
@mulundapm 
@KillerX 
comments?

**Comment by KillerX** [comment]
> This should be a generic standalone service which we can copy-paste when integrating with other systems.
I would prefer to think of this as a module in the system. With an interface something like:

```golang
interface translateCallback {
    updateTranslation(id, lang, string, ...)
}

type TranslationClient struct { ... }

func (tc TranslationClient) sendToTranslation(id, originalLang, string, ...) {...}
```
Then if we want we can easily split it into a service but IMO a service for now will just complicate things for no good reason.

**Comment by andreasgan** [comment]
I think maybe "send to translation" is unecessary and it should instead just be immediate. Crowdin lets you add "context" to a string, so if we want to inform the translators that this is a draft, we could write it there.
@mulundapm

**Comment by mulundapm** [comment]
The title or description is usually not ready when place holder is made. As long as it is easy for translator to identify which are draft and that they are not suppose to translate them, it should be fine. To switch over from draft to ready be translated, where should I be doing it?

**Comment by andreasgan** [comment]
Ok so that changes my mind. But my worry with a "send to translation" button is that we might end up never sending certain things to translation.

**Comment by KillerX** [comment]
> Ok so that changes my mind. But my worry with a "send to translation" button is that we might end up never sending certain things to translation.

Maybe some way of having a general overview of untranslated and being able to send from a central place?

**Comment by andreasgan** [comment]
Pris says the title is always ready when a draft is created.
Even if it wasn't, when we change the title in Admin, it should update the "source string" in crowdin so it should be fine either way.
We just need to make description etc nullable and not send it to crowdin if it's empty.
