### ISSUE TITLE
Release v1 - MVP

### ISSUE THREAD

**Issue by andreasgan** [bcc-code/brunstadtv#8]
To be updated..

CMS 
- [x] Manage episodes, seasons, shows, lists and sections.
- [x] Fill with data from old database.
- [x] Continuous sync with the old database.
- [x] #9 

Gql API
- Will not be included in the first version.

**Comment by andreasgan** [comment]
Releasing to prod
- [ ] Infra deploy
- [ ] Mediapackage setup
- [ ] Sync everything into new DB
- [ ] Verify sync to legacy is working correctly

**Comment by KillerX** [comment]
- [ ] Switch deploy to tags
- [ ] Log based alerts for Ingest (OPS)
- [ ] Scale Up DB for Prod
- [ ] Enable Backups, Failover on prod DB
